apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: avahi
  namespace: avahi
spec:
  selector:
    matchLabels:
      app: avahi
  template:
    metadata:
      labels:
        app: avahi
    spec:
      hostNetwork: true
      containers:
      - name: avahi
        image: ghcr.io/coderanger/avahi:latest
